@local_base_url = http://localhost:3000/api
@local_health_url = http://localhost:3000
@auth_resource = auth

###
# @name health
GET {{local_health_url}}/health

###

# @name register
POST {{local_base_url}}/{{auth_resource}}/register
Content-Type: application/json

{
  "username": "John",
  "email": "john@johncoder.com",
  "first_name": "Doe",
  "last_name": "Doe",
  "password": "Test123@"
}

###

# @name login

POST {{local_base_url}}/{{auth_resource}}/login
Content-Type: application/json

{
  "email": "dave@davecoder.com",
  "password": "Test123@"
}

###

# @name logout

POST {{local_base_url}}/{{auth_resource}}/logout
Content-Type: application/json


###

# @name nonexistent

GET {{local_base_url}}/nonexistent
